# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PowerMonitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PowerMonitor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n\tPowerData\x12-\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x1b.PowerData.PowerChannelData\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1al\n\x10PowerChannelData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x62us_voltage\x18\x02 \x01(\x01\x12\x15\n\rshunt_voltage\x18\x03 \x01(\x01\x12\x0f\n\x07\x63urrent\x18\x04 \x01(\x01\x12\r\n\x05power\x18\x05 \x01(\x01\"<\n\x0b\x43ontrolData\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x08\x12\x0c\n\x04stop\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PowerMonitor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POWERDATA']._serialized_start=56
  _globals['_POWERDATA']._serialized_end=271
  _globals['_POWERDATA_POWERCHANNELDATA']._serialized_start=163
  _globals['_POWERDATA_POWERCHANNELDATA']._serialized_end=271
  _globals['_CONTROLDATA']._serialized_start=273
  _globals['_CONTROLDATA']._serialized_end=333
# @@protoc_insertion_point(module_scope)
